#Globally disable all toggleable functionality within the async system. Set to true to stop all asynchronous operations.
disabled = false
#Maximum number of threads to use for parallel processing. Set to -1 to use default value. Note: If 'virtualThreads' is enabled, this setting will be ignored.
paraMax = -1
#List of entity class for sync processing.
synchronizedEntities = ["minecraft:item", "minecraft:experience_orb", "minecraft:tnt"]
#Enables parallel processing of entity spawns. Warning, incompatible with VMP mod && Carpet mod lagFreeSpawning rule.
enableAsyncSpawn = false
